name: labcomunica
description: "A new Flutter project."
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: ^3.6.1
  flutter: '^3.24.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.1
  flutter_svg: ^2.0.10+1
  provider: ^6.0.5
  dropdown_button2: ^2.3.9
  mask_text_input_formatter: ^2.9.0
  flutter_launcher_icons: ^0.13.1
  brasil_fields: ^1.15.0
  email_validator: ^3.0.0
  file_picker: ^8.1.2
  intl: ^0.19.0
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  universal_html: ^2.2.4
  flutter_secure_storage: ^9.2.2
  flutter_typeahead: ^4.6.2
  osm_nominatim: ^3.0.1
  mime: ^1.0.6
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/dcomp-logo-ufs.png

